---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgDFE0o/6wncdj638U8fH6TOalywXN42qzXjMQJqhcwvsxACkeFgWeRW4PhlcvrkedA5fw3pcbtweVudyTFHGEhzLWqx/vRbc4/T0G19S4zPgvk0fRovPrQqPVfyWlhpU8IWiyFXC2jqaifaBvc5SuipwCxSauAwsY8gxQHXxOoXJp5wOuj1fMjXU0qWeeIMLJ5jGqxCmNVfOlan/VAUNpFGMlUsPmfcIc03DNLyDm280u1INb6cHk4FhP3Z8Q5u0M6TGXfMAxUCSYz2NljDc0gIvbRNXkO/TiXSu5xvahrWz/Lp6OU17Q2v9Rhk63Dq16K2EzMzoeAFROfptkciXK9UnRUowhNxxSzfW1Mn5fEG0UuIXqPvNQzIcaJvjRd+tO588UWopWiOtHAFUd6/7rgw9RDTBN/FiNbVWRJCTf11lkW2ME8voQQPVb5/ocI7M0FnqEm+P6zGA4Mad6m76hmjGYyLA7k8ohZbw9schPO03tJkPIjks7F57MNvH8xssQ1tsW4WcPBzq0wsWqfQnNnCXXi+ObR+efhTzM6QoKA9Q2A/hVeBIIFLEjY6WonN2mLF/A+4oqHLZE4wzwC79gexAJA8HKIzn2qShxJnwZOjeSM++s48vmp1+ncBv5gHjXTT3+UXdHE2IA0l+QKCz67RYhFC05YKC8YyRX1qn7ZXcCrEMza4Fg5yHHAMUTxGueCg76xGdD0sqfI=
    username: AgBjVhXUjQATc6xA+fOs92pvvHrAfPvOS+lOWOGGeeCnlbZnTJaGCO/9lv8VPpi7T5KyzQoKD7maMcvWsoYTil1chlHwtFXg5ii88lc/2FkQ8yBkK6sfq5IeIRkDAUUEb+BUMaLO9xzzXH8svhkHsvM0xCXpx/ybRpQ3xl37/GU23YrzRIL0tVlE1VnlnOlSSGH8ioDTG3N21DyrPbh1mZ3SHRVsBdEpDp3xP4P6ff8yzQEpkxjmOYlb7lTON98U+NrLhtpC1NmeTTJw71ZTkB3anruj1JX1Soi9u+/p7MKHJKYLdlSo5sWMrrdV/UNPLqB4I/Ib1uBGtMXsG2VgOdbfPNNd0AXwri+Ow6+GJJWavtasI7IoIqATt6J6nnjsNt+T6M80XcE0IqvGEpJ1g2/+lo2FyX7KGoy5kL2+TzGdLUotKw1uTqmOotPZLCBmV+gBGUvcocO8Mg4HsD2gmuuOFL7ZN39Q4aVqrgPKX67vk6qIxtZULqF+zBOK/rQpAMbi+BnuC4qfjB3Oi/4Twb7bW+rqN928f7NrkeKCjD9qxnfDA+6pQjCLG3kEfjvEq25555ZH1RG2MDkAaxpoOGnsRNURAc+N69DyUfb1vNZatf3YD1a54NKXByeRSprImBLAtZnre8v75VTaLOMHjUD4BeOqPnMFcesbour32C9sizGD87lFrExN0TCsSTgbMACm1/qDVg==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
